config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root "tops#index"
  resources :recruits, only: [:index]
  resources :performances, only: [:index]
  resources :philosophies, only: [:index]
  resources :services, only: [:index]
  resources :messages, only: [:index]
  resources :companies, only: [:index]
  resources :electricities, only: [:index]
  resources :contacts, only: [:index]
  resources :engineers, only: [:index]
  resources :constructions, only: [:index]
  resources :privacies, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/top.rb
class Top < ApplicationRecord
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    redirect_to root_path
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :content)
    end
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController

  def index
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

  def index
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/constructions_helper.rb
module ConstructionsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/electricities_helper.rb
module ElectricitiesHelper
end

app/helpers/engineers_helper.rb
module EngineersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/philosophies_helper.rb
module PhilosophiesHelper
end

app/helpers/privacies_helper.rb
module PrivaciesHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/_bottom.html.erb
<footer>
  <div class="bottom-hight">
    <div class="top-inner">
      <h2>ご質問やご相談まずはなんでもお聞かせ下さい。</h2>
      <p>お問い合わせは、以下メールフォームまたはお電話からお寄せください。</p>
      <div class="form">
        <div class="tel">
          Tel:06-6845-7782 Fax:06-6845-7783
        </div>
        <div class="mail">
          <%= link_to "お問い合わせはこちらから", new_contact_path %>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom-row">
    <div class="bottom-inner">
      <ul>
        <li><%= link_to "事業紹介", services_path %></li>
        <li>|</li>
        <li><%= link_to "工事実績", performances_path %></li>
        <li>|</li>
        <li><%= link_to "採用情報", recruits_path %></li>
        <li>|</li>
        <li><%= link_to "企業理念", philosophies_path %></li>
        <li>|</li>
        <li><%= link_to "会社概要", companies_path %></li>
        <li>|</li>
        <li><%= link_to "プライバシーポリシー", privacies_path %></li>
        <li>|</li>
        <li><%= link_to "サイトマップ", root_path %></li>
      </ul>
      <p>Copyright(C) 2019- 株式会社トライズCO.,LTD All right Reserved.</p>
    </div>
  </div>
</footer>

app/views/tops/_top.html.erb
<header>
  <div class="top">
    <h1>クリーン事業をお探しなら株式会社トライズにお任せください！</h1>
  </div>
  <div class="info">
    <div class="logo">
      <%= link_to image_tag("/logo.png"), root_path %>
    </div>
    <div class="contact">
      <span>TEL:06-6845-7782<br>
          FAX:06-6845-7783</span>
    </div>
  </div>
  <div class="nav">
    <ul class="nav-menu">
      <li class="menu__single"><%= link_to "TOP", root_path %></li>
      <li class="menu__single"><%= link_to "事業内容", services_path %>
        <ul class="menu__second-level">
          <li><%= link_to "クリーン事業", constructions_path %></li>
          <li><%= link_to "建築設備事業", engineers_path %></li>
          <li><%= link_to "通信事業", electricities_path %></li>
        </ul>
      </li>
      <li class="menu__single"><%= link_to "工事実績", performances_path %></li>
      <li class="menu__single"><%= link_to "会社概要", companies_path %>
        <ul class="menu__second-level">
          <li><%= link_to "企業理念", philosophies_path %></li>
          <li><%= link_to "代表挨拶", messages_path %></li>
        </ul>
      </li>
      <li class="menu__single"><%= link_to "採用情報", recruits_path %></li>
    </ul>
  </div>
</header>

app/views/tops/index.html.erb
<%= render 'tops/top' %>
<ul class="slider">
  <li><img src="top_rinen.jpg" alt="top_rinen"></li>
  <li><img src="top_cllean.jpg" alt="top_cllean"></li>
  <li><img src="top_setubi.jpg" alt="top_setubi"></li>
  <li><img src="top_tuusin.jpg" alt="top_tuusin"></li>
</ul>
<div class="container-fluid">
  <h2 class="cont-title">
    事業内容
  </h2>
  <div class="row">
    <div class="business col-sm-4">
      <img src="top_product_im04.jpg">
      <h4><%= link_to "クリーン事業", constructions_path %></h4>
      <p>クリーンルーム内設備を設計から施工管理までトータルにて承ります。これまでに培ってきた多くの実績を生かし、お客様の様々なご要望にお応え致します。</p>
    </div>
    <div class="business col-sm-4">
      <img src="top_product_im02.jpg">
      <h4><%= link_to "建築設備事業", engineers_path %></h4>
      <p>ダイヤモンド穿孔の施工をトータルに承ります。これまで数々の現場で培ってきた多くの実績を生かし、お客様の様々なご要望にお応え致します。</p>
    </div>
    <div class="business col-sm-4">
      <img src="top_product_im03.jpg">
      <h4><%= link_to "通信事業", electricities_path %></h4>
      <p>集合住宅向けインターネット環境設備 の導入に伴う調査、施工、構築までの一連の業務。その他テレビ配等の通信工事を行います。</p>
    </div>
  </div>
  <h3 class="performance">
    新着工事実績
  </h3>
  <table class="table table-hover">
    <tbody>
      <tr>
        <td>2020年4月13日</td>
        <td><span class="new">new</span></td>
        <td><%= link_to "工事更新テスト", root_path %></td>
      </tr>
      <tr>
        <td>2020年2月10日</td>
        <td><span class="new">new</span></td>
        <td><%= link_to "工事中国", root_path %></td>
      </tr>
      <tr>
        <td>2020年2月10日</td>
        <td><span class="new">new</span></td>
        <td><%= link_to "工事情報日本", root_path %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= render 'tops/bottom' %>